# Generated by Django 4.0.4 on 2022-04-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_collection', '0002_rename_bookmark_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='hash',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
