# Generated by Django 4.0.4 on 2022-05-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_collection', '0004_entry_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='hash',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='entry',
            name='uid',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
