# Generated by Django 4.0.4 on 2022-05-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_en', '0003_word_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='uid',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=20),
        ),
    ]
