# Generated by Django 4.0.4 on 2022-05-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_en', '0004_alter_word_uid_alter_word_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('uid', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('word_uid', models.PositiveBigIntegerField(default=0)),
                ('interpretation', models.CharField(max_length=200)),
            ],
        ),
    ]
