# Generated by Django 4.0.4 on 2022-05-21 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_en', '0005_interpretation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interpretation',
            name='word_uid',
        ),
        migrations.AddField(
            model_name='interpretation',
            name='word',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vocabulary_en.word'),
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('uid', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('example', models.TextField()),
                ('interpretation', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vocabulary_en.interpretation')),
            ],
        ),
    ]
