# Generated by Django 4.0.4 on 2022-05-27 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_en', '0006_remove_interpretation_word_uid_interpretation_word_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouchHistory',
            fields=[
                ('uid', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('rate', models.SmallIntegerField(default=0)),
                ('touchee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vocabulary_en.word')),
            ],
        ),
    ]
