# Generated by Django 4.0.4 on 2022-05-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_en', '0008_alter_touchhistory_touchee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touchhistory',
            name='touchee',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
