# Generated by Django 4.0.4 on 2022-05-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_en', '0009_alter_touchhistory_touchee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touchhistory',
            name='touchee',
        ),
    ]
