# Generated by Django 4.0.4 on 2022-05-28 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_en', '0011_touchhistory_touchee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', related_query_name='interpretation', to='vocabulary_en.word'),
        ),
    ]
