# Generated by Django 4.0.4 on 2022-05-28 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_en', '0012_alter_interpretation_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touchhistory',
            name='touchee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary_en.word'),
        ),
    ]
