# Generated by Django 4.0.4 on 2022-05-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='complete_time',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
