# Generated by Django 4.0.4 on 2022-05-25 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_entry_complete_time_entry_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='status',
            new_name='completed',
        ),
    ]
