# Generated by Django 4.0.4 on 2022-05-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_rename_status_entry_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='description',
            new_name='url',
        ),
    ]
